---
- name: prepare modifications
  sudo: yes
  template:
    src: modify.ldif.j2
    dest: /tmp/modify.ldif
    owner: root
    group: root

- name: modify ldap
  sudo: yes
  shell: ldapmodify -Y EXTERNAL -H ldapi:/// -f /tmp/modify.ldif

- name: prepare top level component
  sudo: yes
  template:
    src: prepare.ldif.j2
    dest: /tmp/prepare.ldif
    owner: root
    group: root

- name: add top level component
  sudo: yes
  shell: ldapadd -Y EXTERNAL -H ldapi:/// -f /tmp/prepare.ldif
