---
- name: install packages
  with_items: "{{ dkim_packages }}"
  pkgng:
    name: "{{ item.name }}"

- name: update opendkim
  shell: make -DBATCH -C /usr/ports/mail/opendkim reinstall clean
  args:
    creates: /usr/local/etc/mail/opendkim.conf.sample


- name: configure dkim service
  template:
    src: milteropendkim.j2
    dest: /etc/rc.conf.d/milteropendkim
    owner: root
    group: wheel

- name: create port config dir
  file:
    path: /var/db/ports/mail_opendkim
    owner: root
    group: wheel
    state: directory

- name: configure port
  template:
    src: port-options.j2
    dest: /var/db/ports/mail_opendkim/options
