---
- name: download squirrelmail
  get_url:
    url: "http://downloads.sourceforge.net/project/squirrelmail/stable/1.4.22/squirrelmail-webmail-1.4.22.tar.gz?r=http%3A%2F%2Fwww.squirrelmail.org%2Fdownload.php&ts=1446033558&use_mirror=liquidtelecom"
    dest: /tmp/squirrelmail.tar.gz
    sha256sum: 286453c7aac6cfd0b78509a597be2f15012f0c0c4abd44328ac4c55fb2d0b847

- name: unpack squirrelmail
  sudo: yes
  unarchive:
    src: /tmp/squirrelmail.tar.gz
    dest: /var/www/html
    copy: no

- name: create directories
  sudo: yes
  with_items: squirrelmail_directories
  file:
    path: "/var/local/squirrelmail/{{ item.name }}"
    owner: www-data
    group: www-data
    state: directory

- name: configure settings
  sudo: yes
  template:
    src: config.php.j2
    dest: /var/www/html/squirrelmail-webmail-1.4.22/config/config.php
    owner: root
    group: root

- name: download change-ldap-pass plugin
  get_url:
    url: http://squirrelmail.org/countdl.php?fileurl=http%3A%2F%2Fwww.squirrelmail.org%2Fplugins%2Fchange_ldappass-2.2-1.4.0.tar.gz
    dest: /tmp/squirrel-ldap.tar.gz
    sha256sum: efe26ddfb2689fa7914b25581606e68c91e5795a4838bd2c27f89172a48ac974

- name: unpack change-ldap-pass plugin
  sudo: yes
  unarchive:
    src: /tmp/squirrel-ldap.tar.gz
    dest: /var/www/html/squirrelmail-webmail-1.4.22/plugins
    copy: no

- name: configure change-ldap-pass plugin
  sudo: yes
  template:
    src: config-ldap.php.j2
    dest: /var/www/html/squirrelmail-webmail-1.4.22/plugins/change_ldappass/config.php
    owner: root
    group: root

- name: download avelsieve plugin
  get_url:
    url: "http://squirrelmail.org/countdl.php?fileurl=http%3A%2F%2Fwww.squirrelmail.org%2Fplugins%2Favelsieve-1.9.9.tar.gz"
    dest: /tmp/avelsieve-1.9.9.tar.gz
    sha256sum: 15881185a6e7c2f27261e10182ec3ad9872ffc835adf527ea0325ae0fe4e3c8c

- name: unpack avelsieve plugin
  sudo: yes
  unarchive:
    src: /tmp/avelsieve-1.9.9.tar.gz
    dest: /var/www/html/squirrelmail-webmail-1.4.22/plugins
    copy: no
