---
- name: install packages
  with_items: "{{ postfix_packages }}"
  pkgng:
    name: "{{ item.name }}"
  notify:
    - restart postfix

- name: confgure postfix
  with_items: "{{ postfix_config }}"
  template:
    src: "{{ item.name }}.j2"
    dest: "/usr/local/etc/postfix/{{ item.name }}"
    owner: root
    group: wheel
  notify:
    - restart postfix
