---
- name: install packages
  with_items: "{{ dovecot_packages }}"
  pkgng:
    name: "{{ item.name }}"

- name: enable dovecot
  template:
    src: dovecot.j2
    dest: /etc/rc.conf.d/dovecot

- name: copy default configuration
  shell: "cp -r /usr/local/etc/dovecot/example-config/* /usr/local/etc/dovecot/"
  args:
    creates: /usr/local/etc/dovecot/dovecot.conf

- name: create private directory
  file:
    path: /usr/local/etc/dovecot/private
    mode: 0750
    state: directory
    owner: root
    group: mail

- name: create directory for domains
  file:
    path: /var/mail/domains
    mode: 0700
    owner: dovecot
    group: dovecot
    state: directory

- name: add dovecot user to mail group
  user:
    name: dovecot
    groups: mail
    append: yes

- name: create port config dir
  file:
    path: /var/db/ports/mail_dovecot2
    owner: root
    group: wheel
    state: directory

- name: configure dovecot port
  template:
    src: port-options.j2
    dest: /var/db/ports/mail_dovecot2/options

- name: update dovecot
  shell: make -DBATCH -C /usr/ports/mail/dovecot2 reinstall clean
  args:
    creates: /usr/local/lib/dovecot/libdovecot-ldap.so

- name: create consul-template directory for dovecot
  file:
    path: "/usr/local/etc/consul-templates/{{ dovecot_consul_template_prefix }}"
    state: directory

- name: copy dovecot consul-template files
  with_items: "{{ dovecot_consul_templates }}"
  copy:
    src: "{{ item.filename }}"
    dest: "{{ consul_template_root }}/{{ dovecot_consul_template_prefix }}/{{ item.filename }}"
  notify:
    - restart consul-template

- name: configure consul-template for dovecot
  template:
    src: dovecot.consul.j2
    dest: /usr/local/etc/consul-template.d/dovecot.conf
  notify:
    - restart consul-template
