---
- name: install packages
  with_items: "{{ dovecot_packages }}"
  pkgng:
    name: "{{ item.name }}"
  notify:
    - restart dovecot

- name: enable dovecot
  template:
    src: dovecot.j2
    dest: /etc/rc.conf.d/dovecot
  notify:
    - restart dovecot

- name: copy default configuration
  command: sh -c "cp -r /usr/local/etc/dovecot/example-config/* /usr/local/etc/dovecot/"
  args:
    creates: /usr/local/etc/dovecot/dovecot.conf

- name: create private directory
  file:
    path: /usr/local/etc/dovecot/private
    mode: 0750
    state: directory
    owner: root
    group: mail

- name: create directory for domains
  file:
    path: /var/mail/domains
    mode: 0700
    owner: dovecot
    group: dovecot
    state: directory

- name: configure dovecot
  template:
    src: dovecot.conf.j2
    dest: /usr/local/etc/dovecot/dovecot.conf
    owner: root
    group: wheel
    mode: 0600
  notify:
    - restart dovecot

- name: configure ldap auth
  template:
    src: dovecot-ldap.conf.ext.j2
    dest: /usr/local/etc/dovecot/dovecot-ldap.conf.ext
    owner: root
    group: wheel
    mode: 0600
  notify:
    - restart dovecot

- name: configure dovecot service
  with_items: "{{ dovecot_configs }}"
  template:
    src: "{{ item.name }}.j2"
    dest: "/usr/local/etc/dovecot/conf.d/{{ item.name }}"
    owner: root
    group: wheel
  notify:
    - restart dovecot

- name: install cert
  with_items: "{{ dovecot_certs }}"
  copy:
    src: "{{ item.name }}"
    dest: "/usr/local/etc/dovecot/{{ item.name }}"
    owner: root
    group: wheel
    mode: 0640
  notify:
    - restart dovecot

- name: add dovecot user to mail group
  user:
    name: dovecot
    groups: mail
    append: yes
